// MCP client wrapper around kindroid-mcp. kindroid-mcp is a remote
// Streamable HTTP MCP server (deployed on the NAS) -- Mnemosyne is one of
// its clients, not embedded into it. Mirrors oc-client.ts's shape.
//
// Surfaces only the one tool the KindroidProvider generator path needs.
// Add more as new call sites need them -- three similar lines is better
// than a premature abstraction.

import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StreamableHTTPClientTransport } from "@modelcontextprotocol/sdk/client/streamableHttp.js";
import { log } from "./log.js";
import { MNEMOSYNE_VERSION } from "./version.js";
import { ErrorCode, McpError } from "@modelcontextprotocol/sdk/types.js";
import { extractText, extractStructuredOrParsed } from "./mcp-result.js";

// Minimal shape of a kindroid_advance_group reply -- only the fields
// formatGroupReplies() in kindroid-provider.ts actually uses. kindroid-mcp's
// own message shape carries more (id, timestamp, image_urls, sender_type);
// add fields here only when a real call site needs them.
export interface KindroidGroupReply {
  /** "ai" or "user". */
  sender: string;
  message: string;
  display_name?: string;
}

export interface AdvanceGroupResult {
  /** AI replies generated this call, oldest-first. */
  replies: KindroidGroupReply[];
  ended: "user_turn" | "max_turns";
  turns: number;
  /** Set by kindroid-mcp when the turns ran but reading them back failed.
   * `replies` is empty while `turns` is not -- the generations DID happen
   * upstream, so this is never a retry signal. */
  read_back_error?: string;
}

/**
 * Default per-request timeout for kindroid-mcp calls, overridable with
 * KINDROID_MCP_TIMEOUT_MS.
 *
 * Deliberately well above the MCP SDK's own 60s default. A group beat chains
 * maxTurns SEQUENTIAL model generations before returning, live-measured at
 * ~13s each, so the documented ceiling of 8 turns needs ~105s of generation
 * alone. Erring long is the safe direction here specifically because a
 * mid-flight timeout does not mean "nothing happened" (see callMutatingTool)
 * -- a too-short timeout manufactures exactly the ambiguous, retry-hazardous
 * failure we are trying to avoid, while a too-long one only delays an error
 * on a call that was already lost.
 */
export const DEFAULT_TIMEOUT_MS = 180_000;

export class KindroidClient {
  private client: Client;
  private connected = false;

  constructor(
    private readonly url: URL,
    private readonly authToken?: string,
    private readonly timeoutMs: number = DEFAULT_TIMEOUT_MS,
  ) {
    this.client = new Client(
      { name: "mnemosyne-mcp", version: MNEMOSYNE_VERSION },
      { capabilities: {} },
    );
  }

  async connect(): Promise<void> {
    if (this.connected) return;
    const transport = new StreamableHTTPClientTransport(this.url, {
      requestInit: this.authToken
        ? { headers: { Authorization: `Bearer ${this.authToken}` } }
        : undefined,
    });
    await this.client.connect(transport);
    this.connected = true;
    log.info("kindroid-client", "connected", { url: this.url.toString() });
  }

  async close(): Promise<void> {
    if (!this.connected) return;
    await this.client.close();
    this.connected = false;
  }

  /**
   * Call a kindroid-mcp tool that MUTATES a real conversation, and make a
   * failure say so.
   *
   * Every tool this client calls has side effects that outlive the request:
   * a message is posted, replies are generated by a paid model and persisted
   * to a chat a human will read. So when one of these calls fails, "did
   * anything actually happen?" is not answerable from here -- the request may
   * have been completed server-side after we stopped waiting. A caller that
   * treats the error as "nothing happened" and retries duplicates real
   * messages in someone's chat history.
   *
   * A TIMEOUT is the case where mutation is likely rather than merely
   * possible: the request was sent, accepted, and was still being worked on
   * when we gave up. Observed live on 2026-08-23 -- a group advance timed out
   * at 60s having already generated and persisted both AI turns, and from
   * mnemosyne's side that was indistinguishable from a total failure.
   *
   * Note this is a DIFFERENT failure from the one KindroidProvider's
   * read-back guard covers. That one fires when kindroid-mcp caught its own
   * read-back error and returned it as data. A timeout throws at the
   * transport layer, before any result exists to inspect, so it never
   * reaches that check.
   */
  private async callMutatingTool(name: string, args: Record<string, unknown>) {
    await this.connect();
    const start = Date.now();
    try {
      const result = await this.client.callTool(
        { name, arguments: args },
        undefined,
        {
          timeout: this.timeoutMs,
        },
      );
      log.debug("kindroid-client", "tool ok", {
        tool: name,
        ms: Date.now() - start,
      });
      return result;
    } catch (err) {
      const ms = Date.now() - start;
      const timedOut =
        err instanceof McpError && err.code === ErrorCode.RequestTimeout;
      log.error("kindroid-client", "tool error", {
        tool: name,
        ms,
        timed_out: timedOut,
        msg: (err as Error).message,
      });
      if (timedOut) {
        throw new Error(
          `${name} timed out after ${ms}ms (KINDROID_MCP_TIMEOUT_MS=` +
            `${this.timeoutMs}). The request was accepted, so it may have ` +
            `ALREADY posted a message and generated replies -- do NOT retry ` +
            `blindly, that would duplicate them in a real conversation. ` +
            `Read the target's recent history to see what landed, then ` +
            `continue from there. If beats legitimately need longer than ` +
            `this (a long group turn loop can), raise ` +
            `KINDROID_MCP_TIMEOUT_MS rather than retrying.`,
          { cause: err },
        );
      }
      throw err;
    }
  }

  /** Send a message to a Kindroid AI and return its plain-text reply.
   * `aiId` accepts a raw ai_id or a kindroid-mcp registered friendly name --
   * kindroid_send_message resolves the name server-side. */
  async sendMessage(aiId: string, message: string): Promise<string> {
    const result = await this.callMutatingTool("kindroid_send_message", {
      ai_id: aiId,
      message,
    });
    return extractText(result, "kindroid_send_message");
  }

  /** Drive a group chat's turn loop via kindroid_advance_group and return
   * the AI replies generated. `groupId` accepts a raw group_id or a
   * kindroid-mcp registered friendly name, same as `sendMessage`'s `aiId`. */
  async advanceGroup(
    groupId: string,
    message: string,
    opts?: { maxTurns?: number; allowUser?: boolean },
  ): Promise<AdvanceGroupResult> {
    const args: Record<string, unknown> = { group_id: groupId, message };
    if (opts?.maxTurns !== undefined) args.max_turns = opts.maxTurns;
    if (opts?.allowUser !== undefined) args.allow_user = opts.allowUser;
    const result = await this.callMutatingTool("kindroid_advance_group", args);
    return extractStructuredOrParsed<AdvanceGroupResult>(
      result,
      "kindroid_advance_group",
    );
  }
}
